# Generated by Django 5.2.13 on 2026-04-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_googletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='event_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
